version: "3.8"
services:
  web:
    image: suhag13/basic-dockerize-mern-app:web-1.0
    build:
      context: ./docker-web-app
      dockerfile: Dockerfile.prod
    ports:
      - 80:80
    restart: unless-stopped
  api:
    image: suhag13/basic-dockerize-mern-app:api-1.0
    build:
      context: ./docker-api
      dockerfile: Dockerfile.prod
    ports:
      - 5000:5000
    restart: unless-stopped
  db:
    image: mongo:4.0.28-xenial
    ports:
      - 27017:27017
    volumes:
      - counts:/data/db
    restart: unless-stopped

volumes:
  counts:
