FROM node:21.5.0-alpine3.19

RUN addgroup app && adduser -S -G app app

WORKDIR /app
RUN chown app:app /app

USER app
COPY package*.json yarn.lock ./

RUN yarn install

USER root
COPY . .
RUN chown -R app:app /app

USER app
RUN yarn build

EXPOSE 80

CMD [ "yarn", "preview" ]